# Generated by Django 4.1 on 2023-07-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="img",
            field=models.ImageField(default="avatar.jpg", upload_to="pics"),
        ),
    ]
